credentials:
  usernames:
    admin:
      email: change-me@example.com
      name: Admin
      password: '$2b$12$7FUzZ9rZf2DY1o2rpz3sUuF0j2/2HxbZkF0x5g4rjG0oVw2mE9t5K'  # "admin" (à supprimer/remplacer)
cookie:
  expiry_days: 7
  key: some_signature_key
  name: st_auth
preauthorized:
  emails: []
